"""bench — a reproducible benchmark harness for semantic similarity ensembles.

This package turns the paper's accompanying code into *research infrastructure*:
a single command that evaluates every ensemble method on every benchmark
dataset, with bootstrap confidence intervals, paired significance tests, and
publication-quality tables and figures generated automatically.

Run it with::

    python -m bench                      # all available methods, all datasets
    python -m bench --datasets mc        # one dataset
    python -m bench --methods lr lgp     # a subset of methods
    python -m bench --quick              # fast, CI-friendly configuration

Everything is deterministic given ``--seed`` (default 0), so the numbers in
``results/`` can be regenerated byte-for-byte on any machine.

Scientific-integrity note
-------------------------
The harness only ever reports numbers it actually computes from the data in
``datasets/``. No result is hard-coded. If a method's optional dependency is
not installed, the method is reported as *skipped* rather than guessed.
"""

from .metrics import (
    bootstrap_ci,
    paired_bootstrap_diff,
    pearson_score,
    spearman_score,
)
from .datasets import DATASETS, load_split
from .methods import METHODS, available_methods
from .runner import BenchmarkResult, run_benchmark

__all__ = [
    "DATASETS",
    "METHODS",
    "BenchmarkResult",
    "available_methods",
    "bootstrap_ci",
    "load_split",
    "paired_bootstrap_diff",
    "pearson_score",
    "run_benchmark",
    "spearman_score",
]

__version__ = "0.1.0"
